[[manager.prepend_keymap]]
on   = "V"
run  = "plugin max-preview"

[[manager.prepend_keymap]]
on   = "v"
run  = "plugin hide-preview"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"

# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

keymap = [
	# Exit
	{ on = "<Esc>", run = "escape" },
	{ on = "<C-[>", run = "escape" },
	{ on = "q",     run = "quit" },
	{ on = "й",     run = "quit" },
	{ on = "Q",     run = "quit --no-cwd-file" },
	{ on = "<C-c>", run = "close" },
	{ on = "<C-z>", run = "suspend" },

	# Seeking
	{ on = "K", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "J", run = "seek 5",  desc = "Seek down 5 units in the preview" },

	# ?
	{ on = "-",         run = "link" },
	{ on = "_",         run = "link --relative" },
	{ on = "<C-->",     run = "hardlink" },
	{ on = "<C-s>",     run = "escape --search" },

	# Navigate
	{ on = "<Left>",  run = "leave" },
	{ on = "<Right>", run = "enter" },

	# Hop
	{ on = "<Up>",    run = "arrow -1", desc = "Move cursor up" },
	{ on = "<Down>",  run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "g", "g" ], run = "arrow -99999999", desc = "Move cursor to the top" },
	{ on = "G",          run = "arrow 99999999",  desc = "Move cursor to the bottom" },

	# Rename
	{ on = "<Enter>",   run = "rename --cursor=before_ext" },
	{ on = "r",         run = "rename --cursor=before_ext" },
	{ on = "к",         run = "rename --cursor=before_ext" },

	# Create
	{ on = "a",         run = "create" },

	# Remove
	{ on = "d",         run = "remove" },
	{ on = "D",         run = "remove --permanently" },

	# Exec
	{ on = "e",         run = "shell --interactive" },
	{ on = "E",         run = "shell --block --interactive" },

	# Select
	{ on = "<C-a>",     run = "toggle_all --state=true" },
	{ on = "<C-r>",     run = "toggle_all --state=none" },
	{ on = "<Space>",   run = [ "toggle --state=none"] },
	{ on = "y",         run = "yank" },
	{ on = "x",         run = "yank --cut" },
	{ on = "Y",         run = "unyank" },
	{ on = "X",         run = "unyank" },

	# Paste
	{ on = "p",         run = "paste" },
	{ on = "P",         run = "paste --force" },

	# Hide
	{ on = ".",         run = "hidden toggle" },

	# Open
	{ on = "o", run = "open" },
	{ on = "щ", run = "open" },
	{ on = "O", run = "open --interactive" },
	{ on = "Щ", run = "open --interactive" },

	# Copy
	{ on = [ "c", "c" ], run = "copy path" },
	{ on = [ "c", "d" ], run = "copy dirname" },
	{ on = [ "c", "f" ], run = "copy filename" },
	{ on = [ "c", "n" ], run = "copy name_without_ext" },

	# Filter
	{ on = "F", run = "filter --smart"},

	# Find - locally
	{ on = "f", run = "find --smart"},
	{ on = "n", run = "find_arrow"},
	{ on = "N", run = "find_arrow --previous"},

	# Find - globally
	{ on = "z",         run = "plugin zoxide" },
	{ on = "я",         run = "plugin zoxide" },

	# View
	{ on = [ "m", "s" ], run = "linemode size" },
	{ on = [ "m", "p" ], run = "linemode permissions" },
	{ on = [ "m", "c" ], run = "linemode ctime" },
	{ on = [ "m", "m" ], run = "linemode mtime" },
	{ on = [ "m", "o" ], run = "linemode owner" },
	{ on = [ "m", "n" ], run = "linemode none" },

	# Sort
	{ on = [ "s", "m" ], run = [ "sort modified --reverse=no", "linemode mtime" ] },
	{ on = [ "s", "M" ], run = [ "sort modified --reverse", "linemode mtime" ] },
	{ on = [ "s", "c" ], run = [ "sort created --reverse=no", "linemode ctime" ] },
	{ on = [ "s", "C" ], run = [ "sort created --reverse", "linemode ctime" ] },
	{ on = [ "s", "e" ], run = "sort extension --reverse=no" },
	{ on = [ "s", "E" ], run = "sort extension --reverse" },
	{ on = [ "s", "a" ], run = "sort alphabetical --reverse=no" },
	{ on = [ "s", "A" ], run = "sort alphabetical --reverse" },
	{ on = [ "s", "n" ], run = "sort natural --reverse=no" },
	{ on = [ "s", "N" ], run = "sort natural --reverse" },
	{ on = [ "s", "s" ], run = [ "sort size --reverse=no", "linemode size" ] },
	{ on = [ "s", "S" ], run = [ "sort size --reverse", "linemode size" ] },
	{ on = [ "s", "r" ], run = "sort random --reverse=no" },

	# Goto
	{ on = [ "g", "h" ],       run = "cd ~" },
	{ on = [ "g", "c" ],       run = "cd ~/.config" },
	{ on = [ "g", "l" ],       run = "cd ~/Downloads" },
	{ on = [ "g", "d" ],       run = "cd ~/Documents" },
	{ on = [ "g", "m" ],       run = "cd ~/Movies" },
	{ on = [ "g", "p" ],       run = "cd ~/Documents/_proj" },
	{ on = [ "g", "o" ],       run = "cd ~/Desktop" },

	# Tabs
	{ on = "t", run = "tab_create --current", desc = "Create a new tab with CWD" },

	{ on = "1", run = "tab_switch 0", desc = "Switch to the first tab" },
	{ on = "2", run = "tab_switch 1", desc = "Switch to the second tab" },
	{ on = "3", run = "tab_switch 2", desc = "Switch to the third tab" },
	{ on = "4", run = "tab_switch 3", desc = "Switch to the fourth tab" },
]

[select]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancel selection" },
	{ on = "<C-[>",   run = "close",          desc = "Cancel selection" },
	{ on = "<C-c>",   run = "close",          desc = "Cancel selection" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit the selection" },

	{ on = "k", run = "arrow -1", desc = "Move cursor up" },
	{ on = "j", run = "arrow 1",  desc = "Move cursor down" },

	{ on = "<Up>",   run = "arrow -1", desc = "Move cursor up" },
	{ on = "<Down>", run = "arrow 1",  desc = "Move cursor down" },

	# Help
	{ on = "~",    run = "help", desc = "Open help" },
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[input]

keymap = [
	{ on = "<C-c>",   run = "close",          desc = "Cancel input" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit input" },
	{ on = "<Esc>",   run = "escape",         desc = "Go back the normal mode, or cancel input" },
	{ on = "<C-[>",   run = "escape",         desc = "Go back the normal mode, or cancel input" },

	# Mode
	{ on = "i", run = "insert",                              desc = "Enter insert mode" },
	{ on = "a", run = "insert --append",                     desc = "Enter append mode" },
	{ on = "I", run = [ "move -999", "insert" ],             desc = "Move to the BOL, and enter insert mode" },
	{ on = "A", run = [ "move 999", "insert --append" ],     desc = "Move to the EOL, and enter append mode" },
	# { on = "v", run = "visual",                              desc = "Enter visual mode" },
	# { on = "V", run = [ "move -999", "visual", "move 999" ], desc = "Enter visual mode and select all" },

	# Character-wise movement
	{ on = "h",       run = "move -1", desc = "Move back a character" },
	{ on = "l",       run = "move 1",  desc = "Move forward a character" },
	{ on = "<Left>",  run = "move -1", desc = "Move back a character" },
	{ on = "<Right>", run = "move 1",  desc = "Move forward a character" },
	{ on = "<C-b>",   run = "move -1", desc = "Move back a character" },
	{ on = "<C-f>",   run = "move 1",  desc = "Move forward a character" },

	# Word-wise movement
	{ on = "b",     run = "backward",              desc = "Move back to the start of the current or previous word" },
	{ on = "w",     run = "forward",               desc = "Move forward to the start of the next word" },
	{ on = "e",     run = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },
	{ on = "<A-b>", run = "backward",              desc = "Move back to the start of the current or previous word" },
	{ on = "<A-f>", run = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },

	# Line-wise movement
	{ on = "0",      run = "move -999", desc = "Move to the BOL" },
	{ on = "$",      run = "move 999",  desc = "Move to the EOL" },
	{ on = "<C-a>",  run = "move -999", desc = "Move to the BOL" },
	{ on = "<C-e>",  run = "move 999",  desc = "Move to the EOL" },
	{ on = "<Home>", run = "move -999", desc = "Move to the BOL" },
	{ on = "<End>",  run = "move 999",  desc = "Move to the EOL" },

	# Delete
	{ on = "<Backspace>", run = "backspace",	       desc = "Delete the character before the cursor" },
	{ on = "<Delete>",    run = "backspace --under", desc = "Delete the character under the cursor" },
	{ on = "<C-h>",       run = "backspace",         desc = "Delete the character before the cursor" },
	{ on = "<C-d>",       run = "backspace --under", desc = "Delete the character under the cursor" },

	# Kill
	{ on = "<C-u>", run = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = "<C-k>", run = "kill eol",      desc = "Kill forwards to the EOL" },
	{ on = "<C-w>", run = "kill backward", desc = "Kill backwards to the start of the current word" },
	{ on = "<A-d>", run = "kill forward",  desc = "Kill forwards to the end of the current word" },

	# Cut/Yank/Paste
	{ on = "d", run = "delete --cut",                              desc = "Cut the selected characters" },
	{ on = "D", run = [ "delete --cut", "move 999" ],              desc = "Cut until the EOL" },
	{ on = "c", run = "delete --cut --insert",                     desc = "Cut the selected characters, and enter insert mode" },
	{ on = "C", run = [ "delete --cut --insert", "move 999" ],     desc = "Cut until the EOL, and enter insert mode" },
	{ on = "x", run = [ "delete --cut", "move 1 --in-operating" ], desc = "Cut the current character" },
	{ on = "y", run = "yank",           desc = "Copy the selected characters" },
	{ on = "p", run = "paste",          desc = "Paste the copied characters after the cursor" },
	{ on = "P", run = "paste --before", desc = "Paste the copied characters before the cursor" },

	# Undo/Redo
	{ on = "u",     run = "undo", desc = "Undo the last operation" },
	{ on = "<C-r>", run = "redo", desc = "Redo the last operation" },

	# Help
	{ on = "~",    run = "help", desc = "Open help" },
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[confirm]
keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancel the confirm" },
	{ on = "<C-[>",   run = "close",          desc = "Cancel the confirm" },
	{ on = "<C-c>",   run = "close",          desc = "Cancel the confirm" },
	{ on = "<Enter>", run = "close --submit", desc = "Submit the confirm" },

	{ on = "n", run = "close",          desc = "Cancel the confirm" },
	{ on = "y", run = "close --submit", desc = "Submit the confirm" },

	{ on = "k", run = "arrow -1", desc = "Move cursor up" },
	{ on = "j", run = "arrow 1",  desc = "Move cursor down" },

	{ on = "<Up>",   run = "arrow -1", desc = "Move cursor up" },
	{ on = "<Down>", run = "arrow 1",  desc = "Move cursor down" },

	# Help
	{ on = "~",    run = "help", desc = "Open help" },
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[completion]

keymap = [
	{ on = "<C-c>",   run = "close",                                      desc = "Cancel completion" },
	{ on = "<Tab>",   run = "close --submit",                             desc = "Submit the completion" },
	{ on = "<Enter>", run = [ "close --submit", "close_input --submit" ], desc = "Submit the completion and input" },

	{ on = "<A-k>", run = "arrow -1", desc = "Move cursor up" },
	{ on = "<A-j>", run = "arrow 1",  desc = "Move cursor down" },

	{ on = "<Up>",   run = "arrow -1", desc = "Move cursor up" },
	{ on = "<Down>", run = "arrow 1",  desc = "Move cursor down" },


	# Help
	{ on = "~",    run = "help", desc = "Open help" },
	{ on = "<F1>", run = "help", desc = "Open help" },
]

[help]

keymap = [
	{ on = "<Esc>", run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = "<C-[>", run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = "q",     run = "close",  desc = "Exit the process" },
	{ on = "<C-c>", run = "close",  desc = "Hide the help" },

	# Navigation
	{ on = "k", run = "arrow -1", desc = "Move cursor up" },
	{ on = "j", run = "arrow 1",  desc = "Move cursor down" },

	{ on = "<Up>",   run = "arrow -1", desc = "Move cursor up" },
	{ on = "<Down>", run = "arrow 1",  desc = "Move cursor down" },

	# Filtering
	{ on = "f", run = "filter", desc = "Apply a filter for the help items" },
]